const $=id=>document.getElementById(id),api=FOLSOE_CONFIG.api;let session=sessionStorage.getItem('folsoe-admin')||'',view,loaded=false;
const hash=new URLSearchParams(location.hash.slice(1));if(hash.has('admin')){session=hash.get('admin');sessionStorage.setItem('folsoe-admin',session);history.replaceState(null,'',location.pathname);}
const themes={classic:'Classic Dance · 90 / 00',trance:'Trance',retro:'Retrohits',weekend:'Weekend',fredagsbar:'Fredagsbar',morning:'Morgenshow',nudisco:'Nu disco',popup:'Pop op'};for(const [value,label]of Object.entries(themes)){const o=document.createElement('option');o.value=value;o.textContent=label;$('theme').append(o);}
$('connect').onclick=()=>location.href=api+'/oauth/start';if(api.includes('DIT-PROJEKT')){$('connect').disabled=true;$('config-status').textContent='Udfyld config.js med din Supabase-adresse. Brug START_HER.html i pakken.';}
async function request(path,body){const r=await fetch(api+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-Admin-Token':session},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(12000)});const j=await r.json();if(!r.ok){if(r.status===401){session='';sessionStorage.removeItem('folsoe-admin');$('login').hidden=false;$('panel').hidden=true;}throw Error(j.error||'Forbindelsen svarede ikke');}return j;}
async function action(type,data={}){try{await request('/action',{type,...data});$('notice').textContent='Handlingen er sendt. Status opdateres om et øjeblik.';}catch(e){$('notice').textContent=e.message;}}
for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>{const type=b.dataset.action;if(['reset-points','reset-history','stop'].includes(type)&&!confirm(type==='reset-history'?'Må alle spørgsmål komme igen?':type==='reset-points'?'Nulstil aftenens point? Spørgsmålshistorikken bevares.':'Afslut quizzen? En ufuldstændig købt quiz refunderes.'))return;action(type);};
$('settings').onsubmit=e=>{e.preventDefault();const settings={theme:$('theme').value,difficulty:$('difficulty').value,language:'da',placement:{}};for(const k of ['seconds','interval','roundSize','goal'])settings[k]=Number($(k).value);for(const k of ['x','y','width','height'])settings.placement[k]=Number($(k).value);action('settings',{settings});};
$('copy').onclick=async()=>{const url=new URL('overlay.html',location.href);url.hash='key='+view.overlayKey;try{await navigator.clipboard.writeText(url.href);$('notice').textContent='OBS-adressen er kopieret.';}catch{prompt('Kopiér denne adresse til OBS:',url.href);}};
$('logout').onclick=async()=>{try{await request('/logout',{});}finally{sessionStorage.removeItem('folsoe-admin');location.reload();}};
const names={idle:'Klar til næste quiz',intro:'Quizzen starter',publishing:'Spørgsmålet sendes til chatten',question:'Seerne svarer',reveal:'Det rigtige svar',board:'Resultattavle',break:'Musikpause mellem spørgsmål',finale:'Tak for spillet',paused:'Quizzen er på pause'};
async function poll(){if(session)try{view=await request('/admin');$('login').hidden=true;$('panel').hidden=false;$('status').replaceChildren();for(const [label,ok]of [['Twitch-chat',view.connection.status==='connected'],['Live',view.isLive],['OBS',view.overlayOnline],['Quizkøb åbne',view.rewards.ready]]){const b=document.createElement('span');b.className='badge'+(ok?' good':'');b.textContent=label+' · '+(ok?'ja':'nej');$('status').append(b);}$('phase').textContent=names[view.phase]||view.phase;const cooldown=Math.max(0,Math.ceil((view.rewards.cooldownUntil-view.serverNow)/1000));$('notice').textContent=view.notice||(cooldown?'Næste køb om '+cooldown+' sekunder.':view.rewards.armed&&!view.rewards.ready?'Køb er klargjort og åbner, når alle betingelser er opfyldt.':'');$('bank').textContent=view.available+' ubrugte spørgsmål i dette tema · '+view.seen+' brugt af '+view.total+' i banken';$('log').textContent=view.log.slice().reverse().map(x=>new Date(x.at).toLocaleTimeString('da-DK')+'  '+x.message).join('\n');if(!loaded){loaded=true;for(const k of ['theme','difficulty','seconds','interval','roundSize','goal'])$(k).value=view.settings[k];for(const k of ['x','y','width','height'])$(k).value=view.settings.placement[k];}}catch(e){$('notice').textContent=e.message;$('config-status').textContent=e.message;}finally{setTimeout(poll,3000);}else setTimeout(poll,3000);}poll();
