import {putMany,getAll,clear,delMany,TRACKS,HISTORY,PLANS,SETTINGS,put} from './db.js';
import {norm,download,exportMaster,exportSoundiiz,exportTuneMyMusic,parseImport} from './common.js';
import {SpotifyClient,spotifyTrack} from './spotify.js';
const $=id=>document.getElementById(id);let tracks=[],plans=[],history=[],profiles=[],spotifyPlaylists=[];let currentPlan=null;
const log=m=>{$('log').textContent+=`[${new Date().toLocaleTimeString('da-DK')}] ${m}\n`;$('log').scrollTop=$('log').scrollHeight};
const sp=new SpotifyClient(log);
function tabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.panel).classList.add('active')})}
async function loadAll(){[tracks,plans,history,profiles]=await Promise.all([getAll(TRACKS),getAll(PLANS),getAll(HISTORY),fetch('data/show-profiles.json').then(r=>r.json())]);render();}
function render(){
 $('trackCount').textContent=tracks.length.toLocaleString('da-DK');$('verifiedCount').textContent=tracks.filter(t=>t.verified).length.toLocaleString('da-DK');$('playlistCount').textContent=new Set(tracks.flatMap(t=>t.playlists||[])).size.toLocaleString('da-DK');$('planCount').textContent=plans.length.toLocaleString('da-DK');
 const selectedGenre=$('genreFilter').value,selectedStatus=$('statusFilter').value,q=norm($('search').value);const genres=[...new Set(tracks.map(t=>t.genre).filter(Boolean))].sort();$('genreFilter').innerHTML='<option value="">Alle genrer</option>'+genres.map(g=>`<option ${g===selectedGenre?'selected':''}>${g}</option>`).join('');
 const filtered=tracks.filter(t=>(!q||norm(`${t.artist} ${t.title} ${t.album} ${(t.tags||[]).join(' ')} ${(t.playlists||[]).join(' ')}`).includes(q))&&(!selectedGenre||t.genre===selectedGenre)&&(!selectedStatus||(selectedStatus==='verified'?t.verified:!t.verified))).slice(0,800);
 $('trackRows').innerHTML=filtered.map(t=>`<tr><td><input type="checkbox" data-id="${t.id}"></td><td>${t.artist}</td><td>${t.title}</td><td>${t.album||''}</td><td>${t.year||''}</td><td>${t.genre||''}</td><td>${t.bpm||''}</td><td>${t.camelot||t.key||''}</td><td>${(t.playlists||[]).slice(0,2).join(', ')}</td><td class="${t.verified?'status-ready':'status-warn'}">${t.verified?'Klar':'Kontrol'}</td></tr>`).join('');
 $('showSelect').innerHTML=profiles.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');
}
function playlistCard(p){const img=p.images?.[0]?.url||'';return `<label class="playlist-card"><input type="checkbox" data-playlist="${p.id}"><img src="${img}" alt=""><span class="info"><strong>${p.name}</strong><small>${p.owner?.display_name||''} · ${p.items?.total??p.tracks?.total??0} numre</small></span></label>`}
async function connectSpotify(){await sp.login($('clientId').value)}
async function loadSpotify(){if(!sp.token)throw new Error('Forbind Spotify først.');const me=await sp.profile();$('spotifyStatus').textContent=`Forbundet: ${me.display_name||me.id}`;spotifyPlaylists=await sp.playlists();$('spotifyPlaylists').innerHTML=spotifyPlaylists.map(playlistCard).join('');$('spotifyPlaylistTotal').textContent=spotifyPlaylists.length;log(`${spotifyPlaylists.length} Spotify-playlister hentet.`)}
async function mergeIncoming(incoming){const map=new Map(tracks.map(t=>[t.id,t]));let added=0,merged=0;for(const t of incoming){if(!t)continue;if(map.has(t.id)){const old=map.get(t.id);map.set(t.id,{...old,...t,genre:old.genre||t.genre,tags:[...new Set([...(old.tags||[]),...(t.tags||[])])],playlists:[...new Set([...(old.playlists||[]),...(t.playlists||[])])],rating:old.rating||0,crowdRating:old.crowdRating||0,lastPlayed:old.lastPlayed||null,playCount:old.playCount||0});merged++}else{map.set(t.id,t);added++}}tracks=[...map.values()];await putMany(TRACKS,tracks);log(`${added} nye numre, ${merged} eksisterende numre flettet.`);render()}
async function importSelectedPlaylists(){const ids=[...document.querySelectorAll('[data-playlist]:checked')].map(x=>x.dataset.playlist);if(!ids.length)return alert('Vælg mindst én playliste.');let incoming=[],done=0;for(const id of ids){const p=spotifyPlaylists.find(x=>x.id===id);log(`Importerer ${p.name}...`);const items=await sp.playlistItems(id);incoming.push(...items.map(x=>spotifyTrack(x,`Spotify playlist: ${p.name}`,p.name)).filter(Boolean));done++;$('syncProgress').style.width=`${done/ids.length*100}%`}await mergeIncoming(incoming)}
async function importLiked(){log('Importerer Liked Songs...');const items=await sp.savedTracks();await mergeIncoming(items.map(x=>spotifyTrack(x,'Spotify Liked Songs','Liked Songs')).filter(Boolean))}
async function importRecent(){const items=await sp.recent();const incoming=items.map(x=>{const t=spotifyTrack(x,'Spotify Recently Played','Recently Played');if(t){t.lastPlayed=x.played_at;t.playCount=1}return t}).filter(Boolean);await mergeIncoming(incoming)}
async function importTop(){const items=await sp.topTracks();await mergeIncoming(items.map(x=>{const t=spotifyTrack(x,'Spotify Top Tracks',`Top Tracks ${x.period}`);if(t)t.tags.push(`Top ${x.period}`);return t}).filter(Boolean))}
async function fileImport(e){for(const f of e.target.files){const parsed=parseImport(await f.text(),f.name);await mergeIncoming(parsed)}e.target.value=''}
function eligible(t,p,cutoff){const text=norm(`${t.genre} ${t.subgenre} ${(t.tags||[]).join(' ')} ${(t.playlists||[]).join(' ')}`);const genre=p.genres.includes('Any')||p.genres.some(g=>text.includes(norm(g)));const en=Number(t.energy||5)>=p.minEnergy&&Number(t.energy||5)<=p.maxEnergy;const bpm=!t.bpm||(t.bpm>=p.bpmMin&&t.bpm<=p.bpmMax);const recent=t.lastPlayed&&new Date(t.lastPlayed)>=cutoff;return genre&&en&&bpm&&!recent&&t.spotifyUri}
function score(t){return Number(t.rating||0)*3+Number(t.crowdRating||0)*3+(t.verified?3:0)+(t.popularity||0)/25+Math.random()*4}
function generatePlan(){const p=profiles.find(x=>x.id===$('showSelect').value),date=$('showDate').value||new Date().toISOString().slice(0,10),cutoff=new Date();cutoff.setDate(cutoff.getDate()-p.repeatDays);const pool=tracks.filter(t=>eligible(t,p,cutoff)).sort((a,b)=>score(b)-score(a));const selected=[],artists=new Map();for(const t of pool){const a=norm(t.artist);if((artists.get(a)||0)>=2)continue;selected.push(t);artists.set(a,(artists.get(a)||0)+1);if(selected.length>=p.targetTracks)break}selected.sort((a,b)=>Number(a.energy||5)-Number(b.energy||5)||Number(a.bpm||0)-Number(b.bpm||0));currentPlan={id:crypto.randomUUID(),showId:p.id,showName:p.name,date,status:'Draft',trackIds:selected.map(t=>t.id),createdAt:new Date().toISOString()};renderPlan()}
function renderPlan(){const list=currentPlan.trackIds.map(id=>tracks.find(t=>t.id===id)).filter(Boolean);$('planTitle').textContent=`${currentPlan.showName} — ${currentPlan.date} — ${list.length} numre`;$('planRows').innerHTML=list.map((t,i)=>`<tr><td>${i+1}</td><td>${t.artist}</td><td>${t.title}</td><td>${t.bpm||''}</td><td>${t.camelot||t.key||''}</td><td>${t.energy||''}</td><td>${(t.tags||[]).join(', ')}</td></tr>`).join('');$('planDialog').showModal()}
async function approvePlan(){currentPlan.status='Approved';await put(PLANS,currentPlan);plans=await getAll(PLANS);render();log('Showplan godkendt og gemt.')}
async function publishPlan(){if(!sp.token)return alert('Forbind Spotify først.');const list=currentPlan.trackIds.map(id=>tracks.find(t=>t.id===id)).filter(Boolean),uris=list.map(t=>t.spotifyUri).filter(Boolean);const p=await sp.createPlaylist(`DJ FOLSOE — ${currentPlan.showName.toUpperCase()} — ${currentPlan.date}`,'Generated by DJ FOLSOE MUSIC SERVER V1800',uris,false);log(`Spotify-playliste oprettet: ${p.external_urls.spotify}`);window.open(p.external_urls.spotify,'_blank')}
async function markSelected(verified){const ids=new Set([...document.querySelectorAll('#trackRows input:checked')].map(x=>x.dataset.id));const changed=[];tracks=tracks.map(t=>{if(ids.has(t.id)){const n={...t,verified};changed.push(n);return n}return t});await putMany(TRACKS,changed);render()}
async function deleteSelected(){const ids=[...document.querySelectorAll('#trackRows input:checked')].map(x=>x.dataset.id);await delMany(TRACKS,ids);tracks=tracks.filter(t=>!ids.includes(t.id));render()}
async function exportWebsite(){download('music-database.json',JSON.stringify(tracks.map(({source,...t})=>t),null,2),'application/json')}
async function resetDb(){if(!confirm('Slet hele Music Server-databasen i denne browser?'))return;await Promise.all([clear(TRACKS),clear(HISTORY),clear(PLANS)]);tracks=[];plans=[];history=[];render()}
async function init(){tabs();$('clientId').value=localStorage.getItem('djf_spotify_client')||'';try{if(await sp.handleCallback())log('Spotify-login gennemført.')}catch(e){log('Spotify-fejl: '+e.message)}await loadAll();if(sp.token)loadSpotify().catch(e=>log(e.message))}
$('connectSpotify').onclick=()=>connectSpotify().catch(e=>log(e.message));$('refreshSpotify').onclick=()=>loadSpotify().catch(e=>log(e.message));$('importPlaylists').onclick=()=>importSelectedPlaylists().catch(e=>log(e.message));$('importLiked').onclick=()=>importLiked().catch(e=>log(e.message));$('importRecent').onclick=()=>importRecent().catch(e=>log(e.message));$('importTop').onclick=()=>importTop().catch(e=>log(e.message));$('fileImport').onchange=e=>fileImport(e).catch(x=>log(x.message));['search','genreFilter','statusFilter'].forEach(id=>$(id).oninput=render);$('verifySelected').onclick=()=>markSelected(true);$('reviewSelected').onclick=()=>markSelected(false);$('deleteSelected').onclick=deleteSelected;$('exportMaster').onclick=()=>download('dj-folsoe-master-library.csv',exportMaster(tracks));$('exportSoundiiz').onclick=()=>download('dj-folsoe-soundiiz.csv',exportSoundiiz(tracks));$('exportTMM').onclick=()=>download('dj-folsoe-tunemymusic.csv',exportTuneMyMusic(tracks));$('exportWebsite').onclick=exportWebsite;$('generatePlan').onclick=generatePlan;$('closePlan').onclick=()=>$('planDialog').close();$('approvePlan').onclick=approvePlan;$('publishPlan').onclick=()=>publishPlan().catch(e=>log(e.message));$('planMaster').onclick=()=>{const list=currentPlan.trackIds.map(id=>tracks.find(t=>t.id===id)).filter(Boolean);download(`${currentPlan.showId}-${currentPlan.date}.csv`,exportMaster(list))};$('planSoundiiz').onclick=()=>{const list=currentPlan.trackIds.map(id=>tracks.find(t=>t.id===id)).filter(Boolean);download(`${currentPlan.showId}-${currentPlan.date}-soundiiz.csv`,exportSoundiiz(list))};$('planTMM').onclick=()=>{const list=currentPlan.trackIds.map(id=>tracks.find(t=>t.id===id)).filter(Boolean);download(`${currentPlan.showId}-${currentPlan.date}-tunemymusic.csv`,exportTuneMyMusic(list))};$('resetDb').onclick=resetDb;init();
