const $=id=>document.getElementById(id);const canvas=$('canvas'),stage=$('stage');let state,offset=0,key='';
if(location.pathname==='/preview')document.body.classList.add('preview');
function resize(){canvas.style.transform=`scale(${Math.min(innerWidth/1920,innerHeight/1080)})`;}addEventListener('resize',resize);resize();
const texts={da:{round:'RUNDE',question:'SPØRGSMÅL',left:'SEKUNDER',top:'AFTENENS TOP 5',empty:'Din plads er ledig.\nSvar i chatten og vær med.',answer:'Skriv !quiz A / B / C',first:'Dit første svar tæller · 100 point for rigtigt svar',answers:'svar modtaget',goal:'FÆLLES MÅL',start:'DIN MUSIK.\nDIT ØJEBLIK.',startCopy:'Tre muligheder. Ét rigtigt svar. Alle kan være med.',ready:'ER DU KLAR?',paused:'QUIZZEN ER PÅ PAUSE',pauseCopy:'Vi er snart tilbage. Dine point er gemt.',reveal:'DET RIGTIGE SVAR',closed:'Svarene er låst',result:'SÅDAN STÅR DET',roundResult:'RUNDENS RESULTAT',resultCopy:'Delt placering ved samme point · Alle kan stadig nå at være med',final:'AFTENENS STJERNER',finalCopy:'Tak, fordi du spillede med. Musikken samler os.',streak:'PÅ STRIBE',publishing:'SPØRGSMÅLET ER PÅ VEJ',pubCopy:'Vi gør chatten klar.',boardFoot:'Du er en del af showet',boardSub:'500 kanalpoint starter næste quiz efter cooldown.'}};
const cat={artist:{da:'HVEM STÅR BAG?'},knowledge:{da:'MUSIKHUKOMMELSE'},title:{da:'FIND TITLEN'},decade:{da:'TILBAGE I TIDEN'}};
function avatar(p){const el=document.createElement('span');el.className='avatar';el.textContent=p.name.slice(0,1).toUpperCase();if(p.avatar&&p.avatar.startsWith('https://')){const img=document.createElement('img');img.src=p.avatar;img.alt='';img.referrerPolicy='no-referrer';img.onerror=()=>img.remove();el.append(img);}return el;}
function board(target,players,full,round=false){target.replaceChildren();const list=players.filter(p=>(round?p.roundPoints:p.points)>0).slice(0,5);if(!list.length){const e=document.createElement('div');e.className='empty';e.textContent=texts[state.settings.language].empty;target.append(e);return;}
 list.forEach((p,i)=>{const row=document.createElement('div');row.className=full?'full-player':'mini-player';row.style.animationDelay=i*55+'ms';const rank=document.createElement('span');rank.className='rank';rank.textContent=String(p.rank).padStart(2,'0');const name=document.createElement('span');name.className='name';name.textContent=p.name;if(full&&p.name.length>18)name.style.fontSize='16px';const points=document.createElement('b');points.className='points';points.textContent=round?p.roundPoints:p.points;row.append(rank,avatar(p),name);if(full&&p.streak>=3){const st=document.createElement('span');st.className='streak';st.textContent=p.streak+' '+texts[state.settings.language].streak;row.append(st);}row.append(points);target.append(row);});}
function render(s){state=s;offset=s.serverNow-Date.now();const t=texts[s.settings.language],q=s.question,p=s.phase,r=s.settings.placement;document.documentElement.lang=s.settings.language;document.body.style.setProperty('--accent',s.theme.color);document.body.style.setProperty('--second',s.theme.secondary);const scale=Math.min(r.width/620,r.height/800);stage.style.left=r.x+(r.width-620*scale)/2+'px';stage.style.top=r.y+(r.height-800*scale)/2+'px';stage.style.transform=`scale(${scale})`;const hidden=['idle','break'].includes(p);stage.className=p+(hidden?' hidden':'');
 $('show').textContent=s.theme.name;$('sub').textContent=s.theme.sub;$('demo').textContent=s.mode==='demo'?'DEMO':'';$('round').textContent=t.round+' '+String(s.round).padStart(2,'0');$('participants').textContent=s.answerCount;$('participants-label').textContent=t.answers;$('goal-label').textContent=t.goal;$('goal-value').textContent=`${s.roundCorrect} / ${s.settings.goal}`;$('goal-fill').style.width=Math.min(100,100*s.roundCorrect/s.settings.goal)+'%';$('instruction').textContent=t.answer;$('instruction-sub').textContent=t.first;
 const isQuestion=['question','reveal'].includes(p);$('main').hidden=!isQuestion;$('main').style.display=isQuestion?'flex':'none';$('hero').hidden=isQuestion;
 if(isQuestion&&q){$('category').textContent=p==='reveal'?t.reveal:(cat[q.category]||cat.knowledge)[s.settings.language];$('question-number').textContent=`${t.question} ${s.number} / ${s.settings.roundSize}`;$('question').textContent=q.text;$('question').style.fontSize=q.text.length>105?'25px':q.text.length>75?'28px':'32px';$('fact').textContent=p==='reveal'?q.fact:'';$('timer-label').textContent=p==='reveal'?t.closed:t.left;$('leader-label').textContent=t.top;board($('mini-board'),s.players,false);$('options').replaceChildren();q.options.forEach((text,i)=>{const row=document.createElement('div');row.className='option'+(p==='reveal'?(i===q.correct?' correct':' wrong'):'');const letter=document.createElement('span');letter.className='letter';letter.textContent='ABC'[i];const answer=document.createElement('span');answer.className='answer';answer.textContent=text;row.append(letter,answer);if(p==='reveal'){const pct=document.createElement('span');pct.className='percent';pct.textContent=(s.answerCount?Math.round(s.distribution[i]/s.answerCount*100):0)+'%';row.append(pct);}$('options').append(row);});if(p==='reveal'){$('instruction').textContent=t.closed;$('instruction-sub').textContent=t.boardFoot;}}
 else{let title=t.start,copy=t.startCopy,kicker=t.ready;const showBoard=['board','finale'].includes(p);if(p==='paused'){title=t.paused;copy=t.pauseCopy;kicker='SPIL MED';}else if(p==='publishing'){title=t.publishing;copy=t.pubCopy;kicker='SPIL MED';}else if(showBoard){title=p==='finale'?t.final:s.number>=s.settings.roundSize?t.roundResult:t.result;copy=p==='finale'?t.finalCopy:t.resultCopy;kicker=p==='finale'?s.theme.name:t.round+' '+s.round;}$('hero-title').textContent=title;$('hero-title').style.whiteSpace='pre-line';$('hero-copy').textContent=copy;$('hero-kicker').textContent=s.startedBy&&p==='intro'?('STARTET AF '+s.startedBy):kicker;$('full-board').hidden=!showBoard;if(showBoard)board($('full-board'),p==='board'&&s.number>=s.settings.roundSize?s.roundPlayers:s.players,true,p==='board'&&s.number>=s.settings.roundSize);$('instruction').textContent=t.boardFoot;$('instruction-sub').textContent=p==='intro'?t.answer:t.boardSub;}
 const newKey=p+q?.id;if(newKey!==key){key=newKey;stage.classList.add('enter');}tick();requestAnimationFrame(fitText);}
function fitText(){const panel=$('question-panel');if($('main').hidden)return;let size=parseFloat($('question').style.fontSize)||32;while(panel.scrollHeight>panel.clientHeight+1&&size>21){$('question').style.fontSize=(--size)+'px';}if(panel.scrollHeight>panel.clientHeight+1){for(const e of document.querySelectorAll('.answer'))e.style.fontSize='19px';$('fact').style.fontSize='14px';}}
function tick(){if(!state)return;const p=state.phase,n=p==='paused'?state.remaining:Math.max(0,Math.ceil((state.deadline-Date.now()-offset)/1000));$('timer').textContent=p==='reveal'?'✓':n;$('ring').style.strokeDashoffset=402.124*(1-(p==='question'?Math.min(1,n/state.settings.seconds):1));stage.classList.toggle('urgent',p==='question'&&n<=5);}
setInterval(tick,200);
const params=new URLSearchParams(location.hash.slice(1));
let access=params.get('key')||sessionStorage.getItem('folsoe-overlay')||'';
if(params.has('key')){sessionStorage.setItem('folsoe-overlay',access);history.replaceState(null,'',location.pathname);}
async function poll(){try{const res=await fetch(FOLSOE_CONFIG.api+'/tick',{method:'POST',headers:{'X-Overlay-Token':access},signal:AbortSignal.timeout(8000)});if(!res.ok)throw Error('Forbindelsen mangler');render(await res.json());}catch(e){if(state&&!['idle','break'].includes(state.phase))render({...state,phase:'paused'});}finally{setTimeout(poll,1500);}}if(access)poll();
