const API='https://api.spotify.com/v1';
const TOKEN='djf_spotify_token',REFRESH='djf_spotify_refresh',CLIENT='djf_spotify_client';
export class SpotifyClient{
 constructor(log=console.log){this.log=log;this.token=localStorage.getItem(TOKEN)||'';this.refresh=localStorage.getItem(REFRESH)||'';this.clientId=localStorage.getItem(CLIENT)||''}
 redirectUri(){return `${location.origin}${location.pathname}`}
 async login(clientId){this.clientId=clientId.trim();if(!this.clientId)throw new Error('Spotify Client ID mangler.');localStorage.setItem(CLIENT,this.clientId);const bytes=crypto.getRandomValues(new Uint8Array(64)),verifier=this.b64(bytes);sessionStorage.setItem('djf_pkce',verifier);const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier)),challenge=this.b64(new Uint8Array(hash));const scope=['playlist-read-private','playlist-read-collaborative','playlist-modify-private','playlist-modify-public','user-library-read','user-read-recently-played','user-top-read','user-read-private'].join(' ');location.href='https://accounts.spotify.com/authorize?'+new URLSearchParams({client_id:this.clientId,response_type:'code',redirect_uri:this.redirectUri(),scope,code_challenge_method:'S256',code_challenge:challenge})}
 b64(bytes){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
 async handleCallback(){const code=new URLSearchParams(location.search).get('code');if(!code)return false;const body=new URLSearchParams({client_id:localStorage.getItem(CLIENT),grant_type:'authorization_code',code,redirect_uri:this.redirectUri(),code_verifier:sessionStorage.getItem('djf_pkce')});const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error(await r.text());const d=await r.json();this.token=d.access_token;this.refresh=d.refresh_token||'';localStorage.setItem(TOKEN,this.token);if(this.refresh)localStorage.setItem(REFRESH,this.refresh);history.replaceState({},'',this.redirectUri());return true}
 async renew(){if(!this.refresh)throw new Error('Spotify-session udløbet. Forbind igen.');const body=new URLSearchParams({client_id:localStorage.getItem(CLIENT),grant_type:'refresh_token',refresh_token:this.refresh});const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error('Kunne ikke forny Spotify-login.');const d=await r.json();this.token=d.access_token;localStorage.setItem(TOKEN,this.token)}
 async api(path,opt={},retry=true){const url=path.startsWith('http')?path:API+path;const r=await fetch(url,{...opt,headers:{Authorization:`Bearer ${this.token}`,'Content-Type':'application/json',...(opt.headers||{})}});if(r.status===401&&retry){await this.renew();return this.api(path,opt,false)}if(r.status===429){const wait=Math.max(1,Number(r.headers.get('Retry-After')||2));this.log(`Spotify rate limit: venter ${wait} sek.`);await new Promise(x=>setTimeout(x,wait*1000));return this.api(path,opt,retry)}if(!r.ok)throw new Error(`${r.status}: ${await r.text()}`);return r.status===204?{}:r.json()}
 async profile(){return this.api('/me')}
 async allPages(path,extract=x=>x.items||[]){let url=path.startsWith('http')?path:API+path,out=[];while(url){const d=await this.api(url);out.push(...extract(d));url=d.next||null}return out}
 async playlists(){return this.allPages('/me/playlists?limit=50')}
 async playlistItems(id){return this.allPages(`/playlists/${id}/items?limit=50`,d=>d.items||[])}
 async savedTracks(){return this.allPages('/me/tracks?limit=50',d=>d.items||[])}
 async recent(){const d=await this.api('/me/player/recently-played?limit=50');return d.items||[]}
 async topTracks(){const periods=['short_term','medium_term','long_term'],out=[];for(const p of periods){const d=await this.api(`/me/top/tracks?limit=50&time_range=${p}`);out.push(...(d.items||[]).map(item=>({item,period:p})))}return out}
 async createPlaylist(name,description,uris,isPublic=false){const p=await this.api('/me/playlists',{method:'POST',body:JSON.stringify({name,description,public:isPublic})});for(let i=0;i<uris.length;i+=100){await this.api(`/playlists/${p.id}/items`,{method:'POST',body:JSON.stringify({uris:uris.slice(i,i+100)})});this.log(`${Math.min(i+100,uris.length)}/${uris.length} tilføjet til ${name}`)}return p}
 logout(){[TOKEN,REFRESH].forEach(x=>localStorage.removeItem(x));this.token='';this.refresh=''}
}
export function spotifyTrack(item,source,playlistName=''){const t=item.track||item.item||item;if(!t||t.type!=='track'||!t.id)return null;return{id:`spotify:${t.id}`,spotifyId:t.id,spotifyUri:t.uri||`spotify:track:${t.id}`,spotifyUrl:t.external_urls?.spotify||'',artist:(t.artists||[]).map(a=>a.name).join('; '),title:t.name||'',album:t.album?.name||'',version:'',year:Number((t.album?.release_date||'').slice(0,4))||null,country:'',label:'',genre:'',subgenre:'',bpm:null,key:'',camelot:'',energy:5,isrc:t.external_ids?.isrc||'',durationMs:t.duration_ms||null,playlists:playlistName?[playlistName]:[],tags:[],rating:0,crowdRating:0,lastPlayed:null,playCount:0,source,verified:true,explicit:!!t.explicit,popularity:t.popularity??null,artwork:t.album?.images?.[1]?.url||t.album?.images?.[0]?.url||'',createdAt:new Date().toISOString()}}
