const $=id=>document.getElementById(id),api=WHEEL_CONFIG.api;let session=sessionStorage.getItem('wheel-admin')||'',view,loaded=false;const hash=new URLSearchParams(location.hash.slice(1));if(hash.has('admin')){session=hash.get('admin');sessionStorage.setItem('wheel-admin',session);history.replaceState(null,'',location.pathname);}
$('connect').onclick=()=>location.href=api+'/oauth/start';
async function request(path,body){const r=await fetch(api+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-Admin-Token':session},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(12000)});const j=await r.json();if(!r.ok){if(r.status===401){session='';sessionStorage.removeItem('wheel-admin');$('login').hidden=false;$('panel').hidden=true;}throw Error(j.error||'Forbindelsen svarede ikke');}return j;}
async function action(type,data={}){try{await request('/action',{type,...data});$('notice').textContent='Handlingen er sendt. Vent på næste statusopdatering.';}catch(e){$('notice').textContent=e.message;}}
for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>{const type=b.dataset.action;if(type==='reset'&&!confirm('Nulstil alle gemte subs og aftenens resultater? Luk først fredagsbaren.'))return;if(type==='cancel'&&!confirm('Afbryd dette spin? Bidrag føres tilbage, fredagsbaren lukkes og cooldown bevares.'))return;action(type);};
function addRow(v={label:'NY UDFORDRING',text:'Skriv udfordringen her.',color:'#ff4faf'}){if($('segments').children.length>=16)return;const row=document.createElement('div');row.className='segment';for(const [key,type,max]of [['label','text',24],['text','text',160],['color','color',7]]){const input=document.createElement('input');input.type=type;input.value=v[key];input.dataset.key=key;input.setAttribute('aria-label',key==='label'?'Feltets titel':key==='text'?'Udfordring':'Farve');if(key==='text')input.className='description';input.maxLength=max;input.required=true;row.append(input);}$('segments').append(row);}
$('add').onclick=()=>addRow();$('remove').onclick=()=>{if($('segments').children.length>6)$('segments').lastChild.remove();};
$('settings').onsubmit=e=>{e.preventDefault();const settings={segments:[...$('segments').children].map(row=>Object.fromEntries([...row.children].map(e=>[e.dataset.key,e.value]))),compact:$('compact').checked,placement:{}};for(const k of ['x','y','width','height'])settings.placement[k]=Number($(k).value);action('settings',{settings});};
$('copy').onclick=async()=>{const url=new URL('overlay.html',location.href);url.hash='key='+view.overlayKey;try{await navigator.clipboard.writeText(url.href);$('notice').textContent='OBS-adressen er kopieret. Hold den privat.';}catch{prompt('Kopiér OBS-adressen:',url.href);}};
$('logout').onclick=async()=>{try{await request('/logout',{});}finally{sessionStorage.removeItem('wheel-admin');location.reload();}};
const names={idle:'Klar',countdown:'Gør klar til spin',spinning:'Hjulet spinner',result:'Resultatet vises',paused:'Hjulet er på pause'};
async function poll(){if(session)try{view=await request('/admin');$('login').hidden=true;$('panel').hidden=false;$('status').replaceChildren();for(const [label,ok]of [['Twitch',view.connection.status==='connected'],['Live',view.isLive],['OBS',view.overlayOnline],['Fredagsbar åben',view.armed],['Kanalpoint-køb',view.rewards.ready]]){const b=document.createElement('span');b.className='badge'+(ok?' good':'');b.textContent=label+' · '+(ok?'ja':'nej');$('status').append(b);}$('count').textContent=view.progress+' / 5';const cool=Math.max(0,Math.ceil((view.cooldownUntil-view.serverNow)/1000));$('summary').textContent=names[view.phase]+' · '+view.queued+' spin i kø · '+view.totalCredits+' subs/resubs denne aften'+(cool?' · Næste spin om '+Math.floor(cool/60)+':'+String(cool%60).padStart(2,'0'):'');$('notice').textContent=view.notice;$('log').textContent=view.log.slice().reverse().map(x=>new Date(x.at).toLocaleTimeString('da-DK')+'  '+x.message).join('\n');$('history').replaceChildren();if(!view.history.length)$('history').textContent='Ingen domme endnu. Weekenden holder vejret.';for(const h of view.history.slice(0,8)){const row=document.createElement('div');row.className='history';const label=document.createElement('b'),detail=document.createElement('small');label.textContent=h.label;detail.textContent=h.startedBy+' · '+new Date(h.at).toLocaleTimeString('da-DK');row.append(label,detail);$('history').append(row);}if(!loaded){loaded=true;view.settings.segments.forEach(addRow);$('compact').checked=view.settings.compact;for(const k of ['x','y','width','height'])$(k).value=view.settings.placement[k];}}catch(e){$('notice').textContent=e.message;$('login-error').textContent=e.message;}finally{setTimeout(poll,3000);}else setTimeout(poll,3000);}poll();

// Optional V1.1 viewer-focused preset; save explicitly through the existing settings form.
const viewerPreset=[{"id": "nitte1", "label": "NITTE", "text": "Ingen udfordring. Chatten slipper med skrækken. Denne gang.", "color": "#25283c"}, {"id": "seerne", "label": "SEERNE DRIKKER", "text": "Fælles, frivillig skål hos seerne! Skriv SKÅL i chatten. Vand og sodavand tæller også.", "color": "#ff4faf"}, {"id": "musikskam", "label": "MUSIKSKAM", "text": "Hvilken sang elsker du i smug? Alle må afsløre én pinlig favorit i chatten. Ingen slipper for kærlig drilleri.", "color": "#d7ff54"}, {"id": "emojidom", "label": "EMOJI-DOM", "text": "Bedøm nummeret, der spiller, med én emoji. Er det ild, kærlighed eller en meget træt kartoffel?", "color": "#9f86ff"}, {"id": "studiet", "label": "STUDIET DRIKKER", "text": "Studiet tager en frivillig skål for seerne. Chatten skriver, hvad der skal skåles for. Vælg selv drikken.", "color": "#ffae45"}, {"id": "side", "label": "VÆLG SIDE", "text": "Chat-duel: 90erne eller 00erne? Skriv dit hold i chatten, og forsvar det med én sætning.", "color": "#60e9ec"}, {"id": "nitte2", "label": "FRIPAS", "text": "Hjulet giver fripas. Skriv PUHA, og lad som om du slet ikke var nervøs.", "color": "#25283c"}, {"id": "minde", "label": "SANGMINDE", "text": "Hvilken sang sender dig direkte tilbage til din ungdom? Skriv titel og dit minde med højst fem ord.", "color": "#ff4faf"}, {"id": "dans", "label": "STUE-DANS", "text": "Rejs dig, eller dans med fra stolen til næste omkvæd. Skriv DANSER i chatten, hvis du er med. Ingen kamera kræves.", "color": "#d7ff54"}, {"id": "syng", "label": "SYNG MED", "text": "Syng med hjemme på næste omkvæd. Skriv MIKROFON, hvis naboerne også får koncert. Deltagelse er helt frivillig.", "color": "#9f86ff"}, {"id": "chatdj", "label": "CHAT-DJ", "text": "Alle må foreslå én fredagsbanger i chatten. DJen vælger blandt forslagene, hvad der passer ind i showet.", "color": "#ffae45"}, {"id": "joke", "label": "CHAT-JOKE", "text": "Giv chatten din dårligste korte joke. Reagér på de andres med HAHA eller AV. Dad-jokes er stærkt mistænkte.", "color": "#60e9ec"}];
const presetButton=document.createElement('button');presetButton.type='button';presetButton.textContent='Indlæs de nye seerudfordringer';presetButton.className='primary';$('add').before(presetButton);
presetButton.onclick=()=>{if(view?.armed||view?.phase!=='idle'){$('notice').textContent='Luk fredagsbaren og vent, til hjulet er færdigt, før du skifter felter.';return;}$('segments').replaceChildren();viewerPreset.forEach(addRow);$('notice').textContent='De nye seerfelter er indlæst i formularen. Tryk Gem hjulet for at bruge dem.';};
