const TITLE='Finally Friday – Weekend Dooms Wheel';
const SEGMENTS=[{"id": "nitte1", "label": "NITTE", "text": "Ingen udfordring. Chatten slipper med skrækken. Denne gang.", "color": "#25283c"}, {"id": "seerne", "label": "SEERNE DRIKKER", "text": "Fælles, frivillig skål hos seerne! Skriv SKÅL i chatten. Vand og sodavand tæller også.", "color": "#ff4faf"}, {"id": "musikskam", "label": "MUSIKSKAM", "text": "Hvilken sang elsker du i smug? Alle må afsløre én pinlig favorit i chatten. Ingen slipper for kærlig drilleri.", "color": "#d7ff54"}, {"id": "emojidom", "label": "EMOJI-DOM", "text": "Bedøm nummeret, der spiller, med én emoji. Er det ild, kærlighed eller en meget træt kartoffel?", "color": "#9f86ff"}, {"id": "studiet", "label": "STUDIET DRIKKER", "text": "Studiet tager en frivillig skål for seerne. Chatten skriver, hvad der skal skåles for. Vælg selv drikken.", "color": "#ffae45"}, {"id": "side", "label": "VÆLG SIDE", "text": "Chat-duel: 90erne eller 00erne? Skriv dit hold i chatten, og forsvar det med én sætning.", "color": "#60e9ec"}, {"id": "nitte2", "label": "FRIPAS", "text": "Hjulet giver fripas. Skriv PUHA, og lad som om du slet ikke var nervøs.", "color": "#25283c"}, {"id": "minde", "label": "SANGMINDE", "text": "Hvilken sang sender dig direkte tilbage til din ungdom? Skriv titel og dit minde med højst fem ord.", "color": "#ff4faf"}, {"id": "dans", "label": "STUE-DANS", "text": "Rejs dig, eller dans med fra stolen til næste omkvæd. Skriv DANSER i chatten, hvis du er med. Ingen kamera kræves.", "color": "#d7ff54"}, {"id": "syng", "label": "SYNG MED", "text": "Syng med hjemme på næste omkvæd. Skriv MIKROFON, hvis naboerne også får koncert. Deltagelse er helt frivillig.", "color": "#9f86ff"}, {"id": "chatdj", "label": "CHAT-DJ", "text": "Alle må foreslå én fredagsbanger i chatten. DJen vælger blandt forslagene, hvad der passer ind i showet.", "color": "#ffae45"}, {"id": "joke", "label": "CHAT-JOKE", "text": "Giv chatten din dårligste korte joke. Reagér på de andres med HAHA eller AV. Dad-jokes er stærkt mistænkte.", "color": "#60e9ec"}];
function initial(){return {phase:'idle',armed:false,isLive:false,chatReady:false,rewardId:'',rewardPaused:true,credits:0,totalCredits:0,source:'',startedBy:'',redemptionId:'',spentCredits:0,spin:null,round:0,deadline:0,cooldownUntil:0,notice:'',log:[],outbox:[],recentEvents:[],recentNotices:[],history:[],pulseUntil:0,settings:{segments:structuredClone(SEGMENTS),compact:true,placement:{x:1260,y:120,width:620,height:820}}};}
function log(s,message,kind='info',now=Date.now()){s.log.push({at:now,message,kind});s.log=s.log.slice(-40);}
function ready(s,heartbeat,now){return s.armed&&s.isLive&&s.chatReady&&now-heartbeat<25000&&s.phase==='idle'&&now>=s.cooldownUntil;}
function buyReady(s,heartbeat,now){return ready(s,heartbeat,now)&&!!s.rewardId&&s.credits<5;}
function job(s,redemption,statusValue){if(redemption&&!s.outbox.some(j=>j.redemption===redemption))s.outbox.push({id:crypto.randomUUID(),type:'settle',status:'pending',redemption,statusValue});}
function number(){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296;}
function start(s,source,name,id,now,random){const index=Math.floor(random()*s.settings.segments.length),n=s.settings.segments.length,jitter=(random()-.5)*.5;s.round++;s.source=source;s.startedBy=name||'Fællesskabet';s.spentCredits=source==='subs'?5:0;if(s.spentCredits)s.credits-=5;s.redemptionId=id||'';s.spin={id:crypto.randomUUID(),index,segments:structuredClone(s.settings.segments),rotation:360*7-(index+.5+jitter)*360/n,startAt:now+4000,duration:11000};s.phase='countdown';s.deadline=now+4000;s.notice='';log(s,'Spin '+s.round+' startet: '+s.startedBy+' · '+(source==='points'?'25.000 kanalpoint':source==='subs'?'5 subs/resubs':'manuelt'),'info',now);}
function cancel(s,now,reason){if(['countdown','spinning','paused'].includes(s.phase)){s.credits+=s.spentCredits;s.spentCredits=0;job(s,s.redemptionId,'CANCELED');s.redemptionId='';s.cooldownUntil=Math.max(s.cooldownUntil,now+600000);}s.phase='idle';s.deadline=0;s.notice=reason;log(s,reason,'info',now);}
function transition(state,a,{now=Date.now(),heartbeat=now,random=number}={}){const s=structuredClone(state);if(a.eventId){if(s.recentEvents.includes(a.eventId))return s;s.recentEvents.push(a.eventId);s.recentEvents=s.recentEvents.slice(-3000);}try{
 if(a.type==='credit'){if(a.noticeId&&s.recentNotices.includes(a.noticeId))return s;if(a.noticeId){s.recentNotices.push(a.noticeId);s.recentNotices=s.recentNotices.slice(-3000);}if(s.armed){s.credits++;s.totalCredits++;s.pulseUntil=now+7000;log(s,(a.name||'En seer')+' · '+a.kind+' · '+s.credits+' gemte subs/resubs','info',now);}}
 else if(a.type==='purchase'){if(a.cost!==25000||!buyReady(s,heartbeat,now)){job(s,a.id,'CANCELED');log(s,'Køb refunderes til '+a.name+': hjulet er ikke klar.','info',now);}else start(s,'points',a.name,a.id,now,random);}
 else if(a.type==='open'){if(!s.chatReady)throw Error('Forbind Twitch først.');s.armed=true;s.notice='';log(s,'Fredagsbaren er åbnet. Subs/resubs tælles fra nu.','info',now);}
 else if(a.type==='close'){s.armed=false;log(s,'Nye bidrag er lukket. Gemte subs/resubs bevares.','info',now);}
 else if(a.type==='start'){if(!ready(s,heartbeat,now))throw Error('Åbn hjulet, gå live, og start OBS. Vent også på cooldown.');start(s,'manual','Studiet','',now,random);}
 else if(a.type==='cancel'){if(!['countdown','spinning','paused'].includes(s.phase))throw Error('Der er intet aktivt spin at afbryde.');cancel(s,now,'Spin afbrudt. Kanalpoint returneres, eller de fem subs lægges tilbage.');s.armed=false;}
 else if(a.type==='resume'){if(s.phase!=='paused')throw Error('Hjulet er ikke på pause.');if(!s.isLive||!s.chatReady||now-heartbeat>=25000)throw Error('Twitch og OBS skal være klar først.');s.phase='countdown';s.deadline=now+4000;s.spin.startAt=now+4000;s.notice='Samme udfald vises efter genoptagelse.';}
 else if(a.type==='online')s.isLive=true;
 else if(a.type==='offline'){s.isLive=false;s.armed=false;if(['countdown','spinning','paused'].includes(s.phase))cancel(s,now,'Streamen sluttede. Det afbrudte spin er ført tilbage.');}
 else if(a.type==='revoked'){s.chatReady=false;s.armed=false;if(['countdown','spinning'].includes(s.phase)){s.phase='paused';s.deadline=0;}s.notice='Twitch-forbindelsen skal repareres.';}
 else if(a.type==='reset'){if(s.armed||['countdown','spinning','paused'].includes(s.phase))throw Error('Luk hjulet og afslut dit spin først.');s.credits=0;s.totalCredits=0;s.history=[];s.round=0;s.spin=null;s.phase='idle';s.notice='Ny aften. Tælleren er nulstillet; en igangværende cooldown bevares.';}
 else if(a.type==='settings'){if(s.armed||s.phase!=='idle')throw Error('Luk hjulet og vent til resultatvisningen er slut før ændringer.');const x=a.settings;if(!Array.isArray(x.segments)||x.segments.length<6||x.segments.length>16)throw Error('Brug mellem 6 og 16 felter.');const segments=x.segments.map((v,i)=>{const label=String(v.label||'').trim(),text=String(v.text||'').trim();if(!label||label.length>24||!text||text.length>160||!/^#[a-f0-9]{6}$/i.test(v.color))throw Error('Hvert felt kræver titel (maks. 24 tegn), tekst (maks. 160 tegn) og farve.');return {id:'segment-'+i,label,text,color:v.color};});const r=x.placement;if(!r||!['x','y','width','height'].every(k=>Number.isFinite(r[k]))||r.x<0||r.y<0||r.width<400||r.height<530||r.x+r.width>1920||r.y+r.height>1080)throw Error('Placeringen skal være inden for 1920 × 1080.');s.settings={segments,compact:!!x.compact,placement:{x:r.x,y:r.y,width:r.width,height:r.height}};s.spin=null;s.notice='Indstillinger gemt.';}
 else if(a.type==='tick'){
  if(['countdown','spinning'].includes(s.phase)&&now-heartbeat>25000){s.phase='paused';s.deadline=0;s.notice='OBS svarer ikke. Åbn overlayet og tryk Fortsæt.';}
  else if(s.phase==='countdown'&&now>=s.deadline){s.phase='spinning';s.deadline=s.spin.startAt+s.spin.duration;}
  else if(s.phase==='spinning'&&now>=s.deadline){s.phase='result';s.deadline=now+18000;s.cooldownUntil=now+600000;const result=s.spin.segments[s.spin.index];s.history.unshift({at:now,round:s.round,label:result.label,text:result.text,startedBy:s.startedBy,source:s.source});s.history=s.history.slice(0,20);job(s,s.redemptionId,'FULFILLED');s.redemptionId='';s.spentCredits=0;log(s,'Hjulet valgte: '+result.label,'result',now);}
  else if(s.phase==='result'&&now>=s.deadline){s.phase='idle';s.deadline=0;}
 }
 if(s.phase==='idle'&&s.credits>=5&&ready(s,heartbeat,now))start(s,'subs','Fællesskabet','',now,random);
 }catch(e){s.notice=e.message;log(s,e.message,'error',now);}return s;}
function effectResult(state,j,result,{now=Date.now(),error=''}={}){const s=structuredClone(state);if(error){const item=s.outbox.find(v=>v.id===j.id);if(item){item.status='pending';item.retryAt=now+30000;}s.notice='Twitch-afregning afventer forbindelse.';log(s,error,'error',now);}else s.outbox=s.outbox.filter(v=>v.id!==j.id);return s;}
function publicState(s,heartbeat,now=Date.now()){return {title:TITLE,phase:s.phase,serverNow:now,deadline:s.deadline,settings:s.settings,spin:s.spin,round:s.round,credits:s.credits,totalCredits:s.totalCredits,queued:Math.floor(s.credits/5),progress:s.credits%5,startedBy:s.startedBy,source:s.source,cooldownUntil:s.cooldownUntil,pulseUntil:s.pulseUntil,notice:s.notice,armed:s.armed,isLive:s.isLive,overlayOnline:now-heartbeat<25000,connection:{status:s.chatReady?'connected':'offline'},rewards:{id:!!s.rewardId,ready:buyReady(s,heartbeat,now)},history:s.history};}
// Count individual chat notifications only. Gift-batch headers would double-count.
function creditFromNotification(e){if(e.source_broadcaster_user_id&&e.source_broadcaster_user_id!==e.broadcaster_user_id)return null;const t=e.notice_type;if(!['sub','resub','sub_gift'].includes(t))return null;if(t==='resub'&&e.resub?.is_gift)return null;return {type:'credit',noticeId:e.message_id||'',name:e.chatter_is_anonymous?'Anonym seer':e.chatter_user_name||'En seer',kind:t==='sub_gift'?'gave-sub':t==='resub'?'resub':'sub'};}

let demoState,demoStart;
function restartDemo(){const now=Date.now();demoStart=now;demoState=initial();Object.assign(demoState,{armed:true,isLive:true,chatReady:true,rewardId:'demo',credits:2,totalCredits:7});demoState=transition(demoState,{type:'purchase',id:'demo-buy',name:'Fredagsbaren',cost:25000},{now,heartbeat:now});render(publicState(demoState,now,now));}
restartDemo();setInterval(()=>{const now=Date.now();if(now-demoStart>38000){restartDemo();return;}demoState=transition(demoState,{type:'tick'},{now,heartbeat:now});render(publicState(demoState,now,now));},250);
