(() => {
  'use strict';

  const API = 'https://djfolsoe-tv-api.sunefolsoe.workers.dev';
  const CHARTS = 'https://folsoetv.dk/charts/';
  const DRAFT_KEY = 'djf_showhub_draft_v1';
  const SHOWS = [
    {id:'trance',name:'TRANCE TUESDAY',short:'TRANCE',tag:'TRANCE / MELODY / RELEASE',type:'UGENTLIG',when:'Tirsdag 18.30–21.30',description:'Uplifting, progressive og klassisk trance. Lange opbygninger og plads til det store øjeblik.',page:'trance-tuesday',chart:'trance_top10',chartName:'Your Favorite Trance Chart',anchor:'trance10',day:2,hour:18,minute:30},
    {id:'eurodance',name:'CLASSIC DANCE',short:'CLASSIC DANCE',tag:'#90 #00 / TO ÅRTIER / ÉT DANSEGULV',type:'UGENTLIG',when:'Torsdag 19.00–21.00',description:'To årtier. Ét dansegulv. Dance fra 1990–2009: Eurodance, house, trance, hands up og hard dance. Store klubhits, glemte favoritter og hænderne i vejret.',page:'eurodance',chart:'eurodance_top10',chartName:"Classic Dance · Glemte favoritter",anchor:'eurodance10',day:4,hour:19,minute:0},
    {id:'retro',name:'RETRO HITS',short:'RETRO HITS',tag:'10 / 20 / 30 / 40 / 50 ÅR',type:'UGENTLIG',when:'Søndag normalt 08.00–12.00',description:'En tidsmaskine gennem de hits, der faktisk lå på hitlisterne. Store minder og sange, du næsten havde glemt.',page:'retro-hits',chart:'retro_top10',chartName:'Back in Time',anchor:'retro10',day:0,hour:8,minute:0},
    {id:'fredagsbar',name:'FREDAGSBAR',short:'FREDAGSBAR',tag:'SIDSTE FREDAG / DANSK KAOS',type:'MÅNEDLIG',when:'Sidste fredag 19.00 til vi går kolde',description:'Musik, ønsker og venner i chatten. Vi starter forholdsvis pænt. Derefter må aftenen selv tage ansvaret.',page:'fredagsbar',chart:'top20',chartName:'FOLSOE Top 20',anchor:'top20',monthly:true},
    {id:'morning',name:'GOOD MORNING TWITCH',short:'MORNING',tag:'KAFFE / RADIOHITS / GOD MORGEN',type:'FLEKSIBEL',when:'Lørdag formiddag og pop-up på fridage',description:'Radiohits, dance-pop, nu-disco og god selskab. Morgenprogrammet dukker op, når der er tid til det.',page:'good-morning-twitch',chart:'top20',chartName:'FOLSOE Top 20',anchor:'top20'},
    {id:'popup',name:'POP UP',short:'POP UP',tag:'BLANDET LANDHANDEL / SURPRISE',type:'POP-UP',when:'Når studiet pludselig tænder',description:'Ingen fast opskrift. En fri aften, en idé eller en raidtrain kan ændre hele planen.',page:'pop-up',chart:'top20',chartName:'FOLSOE Top 20',anchor:'top20'},
    {id:'weekend',name:'WEEKEND',short:'WEEKEND',tag:'GOD MUSIK / GODT SELSKAB / FRI WEEKEND',type:'FLEKSIBEL',when:'Pop-up: fredag eftermiddag–søndag aften',description:'Weekend på din måde. Et frit pop-up-show fra fredag eftermiddag til søndag aften: kendte hits, glemte favoritter, nye fund og musik, der passer til øjeblikket. Godt selskab, plads til ønsker og weekendstemning i top.',page:'weekend',chart:'top20',chartName:'FOLSOE Top 20',anchor:'top20'},
    {id:'nudisco',name:'NU DISCO',short:'NU DISCO',tag:'FUNK / DISCO / NYE GROOVES',type:'POP-UP',when:'Annonceres i Twitch-planen',description:'Discoens sjæl i moderne produktion: funk, disco house, edits og remixes med det rigtige groove.',page:'nu-disco',chart:'top20',chartName:'FOLSOE Top 20',anchor:'top20'}
  ];
  const tr = (key, values) => window.DJF_I18N ? window.DJF_I18N.t(key, values) : key.replace(/\{(\w+)\}/g, (m,k) => values?.[k] ?? m);
  const $ = id => document.getElementById(id);
  const draftEnabled=location.hostname.endsWith('.chatgpt.site')||location.hostname==='localhost'||location.hostname==='127.0.0.1';
  const state = {selected:new URLSearchParams(location.search).get('show') || 'trance',schedule:null,charts:null,live:null,cmsShows:[],draft:{}};
  if(draftEnabled)try {const parsed=JSON.parse(localStorage.getItem(DRAFT_KEY)||'{}');if(parsed&&typeof parsed==='object')state.draft=parsed;} catch {}
  if(!SHOWS.some(s=>s.id===state.selected)) state.selected='trance';

  function showData(base){const edit=draftEnabled?state.draft[base.id]||{}:{};const cms=state.cmsShows.find(x=>whichShow(x.title||x.name)===base.id)||{};return {...base,tag:edit.tag||base.tag,description:edit.description||(base.id==='weekend'&&cms.weekendFormatVersion!==1&&/edm|house|fresh releases|frisk|ny musik/i.test(cms.description||'')?base.description:null)||(base.id==='eurodance'&&/^eurodance$/i.test(cms.title||cms.name||'')?base.description:cms.description)||base.description,chart:edit.chart||base.chart};}
  function dateLabel(date){return new Intl.DateTimeFormat(window.DJF_I18N?.locale || 'da-DK',{timeZone:'Europe/Copenhagen',weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'}).format(date).replace(/^./,c=>c.toUpperCase());}
  function localParts(date){const bits=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Copenhagen',year:'numeric',month:'numeric',day:'numeric',weekday:'short',hour:'numeric',minute:'numeric',hourCycle:'h23'}).formatToParts(date);return Object.fromEntries(bits.map(p=>[p.type,p.value]));}
  function copenhagenDate(y,m,d,h,min){const utc=Date.UTC(y,m,d,h,min);const off=new Intl.DateTimeFormat('en-US',{timeZone:'Europe/Copenhagen',timeZoneName:'shortOffset'}).formatToParts(new Date(utc)).find(p=>p.type==='timeZoneName')?.value||'GMT+1';const match=off.match(/GMT([+-])(\d{1,2})(?::(\d{2}))?/);const minutes=match?(match[1]==='-'?-1:1)*(Number(match[2])*60+Number(match[3]||0)):60;return new Date(utc-minutes*60000);}
  function typicalNext(show){if(show.day===undefined&&!show.monthly)return null;const now=new Date(),p=localParts(now),year=Number(p.year),month=Number(p.month)-1,day=Number(p.day);let result;if(show.monthly){for(let i=0;i<3;i++){const last=new Date(Date.UTC(year,month+i+1,0));const offset=(last.getUTCDay()-5+7)%7;result=copenhagenDate(last.getUTCFullYear(),last.getUTCMonth(),last.getUTCDate()-offset,19,0);if(result>now)break;}}else{const weekday=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(p.weekday);const ahead=(show.day-weekday+7)%7;result=copenhagenDate(year,month,day+ahead,show.hour,show.minute);if(result<=now)result=copenhagenDate(year,month,day+ahead+7,show.hour,show.minute);}return result;}
  function whichShow(title){const n=String(title||'').toLowerCase().replace(/[^a-z0-9æøå]+/g,' ');if(/^weekend\b/.test(n))return'weekend';if(/classic dance|eurodance/.test(n))return'eurodance';if(/trance/.test(n))return'trance';if(/retro/.test(n))return'retro';if(/fredagsbar|friday bar/.test(n))return'fredagsbar';if(/good morning|morgen|morning/.test(n))return'morning';if(/nu disco|nudisco/.test(n))return'nudisco';if(/pop up|popup/.test(n))return'popup';if(/weekend/.test(n))return'weekend';return null;}
  function segments(){const source=state.schedule?.segments||state.schedule?.data?.segments||[];return (Array.isArray(source)?source:[]).filter(x=>!x.canceledUntil&&!x.canceled_until&&Date.parse(x.startTime||x.start_time)>Date.now()-60000).sort((a,b)=>Date.parse(a.startTime||a.start_time)-Date.parse(b.startTime||b.start_time));}
  function nextFor(id){return segments().find(s=>whichShow(s.title)===id);}
  function renderList(){const list=$('showList');list.replaceChildren();SHOWS.forEach((base,i)=>{const s=showData(base),button=document.createElement('button');button.type='button';button.className='show-option'+(s.id===state.selected?' active':'');button.style.setProperty('--show-accent',`var(--${s.id})`);button.setAttribute('aria-pressed',String(s.id===state.selected));const num=document.createElement('span');num.className='option-num';num.textContent=String(i+1).padStart(2,'0');const labels=document.createElement('span');labels.className='option-labels';const title=document.createElement('strong');title.textContent=s.name;const when=document.createElement('small');when.textContent=tr(s.when);labels.append(title,when);const arrow=document.createElement('span');arrow.className='option-arrow';arrow.textContent='↗';button.append(num,labels,arrow);button.addEventListener('click',()=>select(s.id));list.append(button);});}
  function renderSchedule(){const upcoming=segments(),top=upcoming[0];$('globalNext').textContent=top?.title||'Ingen bekræftet udsendelse';$('globalNextTime').textContent=top?dateLabel(new Date(top.startTime||top.start_time)):(state.schedule?'Se Twitch-planen for opdateringer':'Twitch-planen kan ikke hentes lige nu');const s=SHOWS.find(x=>x.id===state.selected),next=nextFor(s.id);if(next){$('showNext').textContent=dateLabel(new Date(next.startTime||next.start_time));$('showNextNote').textContent='Bekræftet i den officielle Twitch-plan.';}else{const typical=typicalNext(s);$('showNext').textContent=typical?dateLabel(typical):'Afventer en dato i Twitch-planen';$('showNextNote').textContent=typical?'Forventet ud fra fast sendetid · endnu ikke bekræftet på Twitch.':'Pop-up: datoen vises først, når showet er lagt i Twitch-planen.';}}
  function renderChart(){const base=SHOWS.find(s=>s.id===state.selected),s=showData(base),use=SHOWS.find(x=>x.chart===s.chart)||base;const titles={top20:'FOLSOE Top 20',trance_top10:'Your Favorite Trance Chart',eurodance_top10:"Classic Dance · Glemte favoritter",retro_top10:'Back in Time'};const anchors={top20:'top20',trance_top10:'trance10',eurodance_top10:'eurodance10',retro_top10:'retro10'};$('chartType').textContent=s.chart==='top20'?'TOP 20':s.short;$('chartTitle').textContent=titles[s.chart]||s.chartName;$('chartSubtitle').textContent=s.chart==='top20'&&s.id!=='weekend'?'Dette show har endnu ikke sit eget chart. Her er den aktuelle FOLSOE Top 20.':(s.id==='weekend'?'Valgfri inspiration til showet — musikken følger stemningen.':'Direkte fra det eksisterende chart-univers.');$('chartLink').href=CHARTS+'#'+(anchors[s.chart]||use.anchor);const list=$('chartRows');list.replaceChildren();if(!state.charts){const p=document.createElement('p');p.className='muted';p.textContent='Chart kan ikke hentes lige nu. Åbn det på FOLSOE TV.';list.append(p);$('chartCount').textContent='—';return;}const arr=state.charts[s.chart]||[];const rows=arr.filter(x=>x.artist||x.title).slice(0,5);$('chartCount').textContent=rows.length?`${rows.length} / ${arr.length}`:'—';if(!rows.length){const p=document.createElement('p');p.className='muted';p.textContent='Chartet afventer næste opdatering i admin.';list.append(p);return;}rows.forEach((r,i)=>{const row=document.createElement('div');row.className='chart-row';const rank=document.createElement('b');rank.textContent=String(r.rank||i+1).padStart(2,'0');const track=document.createElement('span');const title=document.createElement('strong');title.textContent=r.title||'Ukendt titel';const artist=document.createElement('small');artist.textContent=r.artist||'Ukendt artist';track.append(title,artist);row.append(rank,track);list.append(row);});}
  function renderLive(){const data=state.live;const known=data!==null;const live=known&&Boolean(data.live??data.isLive??data.data?.live);$('liveDot').className='signal-dot '+(!known?'checking':live?'onair':'offline');$('liveLabel').textContent=!known?'LIVE-STATUS UTILGÆNGELIG':live?'LIVE NU PÅ TWITCH':'OFF AIR LIGE NU';$('liveDetail').textContent=live?tr('{count} ser med · DJ FOLSOE', {count:Number(data.viewers??data.viewerCount)||0}):'Direkte fra DJ FOLSOE på Twitch';$('channelTitle').textContent=live?(data.title||data.streamTitle||'DJ FOLSOE ER LIVE'):'DJ FOLSOE';$('channelNote').textContent=live?'Udsendelsen kører nu. Gå direkte til Twitch og vær med i chatten.':known?'Næste bekræftede sendetid vises i programvælgeren.':'Kontrollér aktuel status direkte på Twitch.';}
  function select(id){state.selected=id;const url=new URL(location.href);url.searchParams.set('show',id);history.replaceState(null,'',url);const base=SHOWS.find(x=>x.id===id),s=showData(base),i=SHOWS.indexOf(base);document.body.dataset.show=id;$('showIndex').textContent=String(i+1).padStart(2,'0')+' / 08';$('showKind').textContent=tr(s.type);$('showTag').textContent=tr(s.tag);$('showName').textContent=s.name;$('showDescription').textContent=tr(s.description);$('showPage').href='https://folsoetv.dk/shows/'+s.page+'/';renderList();renderSchedule();renderChart();}
  async function get(path){const c=new AbortController(),timer=setTimeout(()=>c.abort(),9000);try{const r=await fetch(API+path,{cache:'no-store',signal:c.signal});if(!r.ok)throw Error(String(r.status));return await r.json();}finally{clearTimeout(timer);}}
  async function refresh(){const results=await Promise.allSettled([get('/api/twitch-schedule'),get('/api/cms/chart-universe'),get('/api/twitch'),get('/api/broadcast')]);if(results[0].status==='fulfilled')state.schedule=results[0].value;if(results[1].status==='fulfilled')state.charts=results[1].value.chartUniverse||results[1].value;if(results[2].status==='fulfilled')state.live=results[2].value;if(results[3].status==='fulfilled'){const core=results[3].value.core||{};state.cmsShows=Array.isArray(core.featuredShows)?core.featuredShows:[];}select(state.selected);renderLive();$('dataNote').textContent=state.schedule?'Sendetider fra den officielle Twitch-plan · tider vist i København · showtekster og charts fra eksisterende admin.':'Twitch-planen svarer ikke lige nu. Faste tider er markeret som forventede; kontrollér Twitch for ændringer.';}
  function tickClock(){const time=new Intl.DateTimeFormat(window.DJF_I18N?.locale || 'da-DK',{timeZone:'Europe/Copenhagen',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date());$('clock').textContent=tr('KØBENHAVN')+' · '+time;}
  if(draftEnabled)window.addEventListener('storage',e=>{if(e.key===DRAFT_KEY){try{state.draft=JSON.parse(e.newValue||'{}');}catch{state.draft={};}select(state.selected);}});
  window.addEventListener('djf:languagechange',()=>{renderSchedule();renderLive();tickClock();});
  tickClock();setInterval(tickClock,30000);select(state.selected);refresh();setInterval(refresh,90000);
})();

/* Load the shared public music-TV identity exactly once. */
(()=>{if(window.DJF_STATION_BOOT||/(?:admin|overlay|streamelements|twitch-connect)/i.test(location.pathname))return;window.DJF_STATION_BOOT=true;
const css=document.createElement('link');css.rel='stylesheet';css.href='/assets/css/station-2026.css?v=1';document.head.append(css);
const js=document.createElement('script');js.src='/assets/js/station-2026.js?v=1';js.defer=true;document.head.append(js);})();
